require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'

  config.vm.provider :openstack do |os|
    os.openstack_auth_url = 'http://10.100.0.1:5000/v2.0'
    os.username           = 'vagrant'
    os.password           = 'password'
    os.tenant_name        = 'vagrant'
    os.flavor             = 'm1.small'
    os.image              = 'Ubuntu 14.04'
    os.floating_ip_pool   = 'public'
    os.security_groups    = ['ssh', 'icmp']
  end
end
