Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "file", source: "important_file", destination: "important_file"
  config.vm.provision "shell", path: "script.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
  config.vm.synced_folder "syncme/", "/opt/syncme"
  config.vm.define "first" do |node|
    node.vm.hostname = "first"
    node.vm.network "forwarded_port", guest: 80, host: 8080
    node.vm.network "private_network", ip: "192.168.50.4"
  end
  config.vm.define "second" do |node|
    node.vm.hostname = "second"
    node.vm.network "forwarded_port", guest: 80, host: 8081
    node.vm.network "private_network", ip: "192.168.50.5"
  end
end
